### PR TITLE
Slides 01 Welcome & Orientation

### PR DESCRIPTION
**Pull request by thebioengineer**
Welcome slides to cover what we will be learning and who we are. 

@mariev  - please add to your slide and we can compile into a PDF!

### CODE REVIEW

**Review by mariev — COMMENTED** [review]
Looks great! Some thoughts re: the last section "where do we go from here"

- How are we using breakout rooms? Will we be monitoring zoom chat for raised hands? DMs? Are we discouraging zoom chat in favor of persistence of slack?
- How can advanced users be helpful? Can ppl self-identify willingness to act as a TA?
-  What repo should people clone? {valtools}? something else?

**Comment by thebioengineer** [comment]
I can add something on breakout rooms - I was thinking the "advanced users" piece would be called out in the "what if this is too basic for me"

I will clarify which repo - I mean this repo to get the exercises

**Comment by thebioengineer** [comment]
@mariev - should have changes we discussed

**Review by mariev — APPROVED** [review]
Added mention of RStudio Cloud space

**Comment by thebioengineer** [comment]
Thanks @mariev!

We should add a thank you to R/pharma to the readme

**Pull request merged**
